# .readthedocs.yml
version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 3.7
  pip_install: true
  requirements: requirements.txt
  install:
    - requirements: requirements.txt
